### ISSUE TITLE
[Question] GPL License

### ISSUE THREAD

**Issue by danieljfarrell** [nschloe/termplotlib#54]
Forgive the mundane question but does the GPLv3 allow me to use termplotlib as a dependency in my BSD open-source project? Or does this require re-licensing my project under GPL? This is a fantastic project 👍 good job.

**Comment by nschloe** [comment]
I'm not a license lawyer, but this is what I understand from reading up on the topic:

You can license your software in any license you like, but if anyone want to use it, she'll have to comply to the licenses of all software packages involved (of course). Since GPL is generally stricter than the BSD, this usually means looking at the GPL. That's why it is customary to license depending software as GPL, too. Otherwise the end user of your software might see only your license and get the impression she can use it under BSD only. Eventually that'd be the mistake of the user (not checking all involved licenses), and she'd be the one to b hold liable, but yeah, BSD licensing would be misleading.

**Comment by danieljfarrell** [comment]
Thanks so much for the summary, I find it so hard to wrap my head around the nuances.

So using it is possible, but in practise it kicks the responsibility to the user. When they do their due diligence and discover a GPL dependency, and if that is something they want to avoid, they might not end up using my project.

I think I got it! Thanks 👍🏻

**Comment by danieljfarrell** [comment]
By the way, I noticed (an earlier version?) on PyPI under MIT https://pypi.org/project/asciiplotlib/ as ASCIIplotlib. If you don’t mind me asking, was this just a philosophical decision to re-license or did you see some advantage?

**Comment by nschloe** [comment]
> was this just a philosophical decision to re-license or did you see some advantage?

It was actually a similar consideration. Note that termplotlib uses gnuplot which has its own license. To be on the safe side, I marked termplotlib GPL.
